#文件上传
#cbs:
#    imagesPaths:
#        file:/E:/img/
#server:
#  port: 8081
#
#
#spring:
#  datasource:
#    url: jdbc:mysql://47.110.241.60/darksouls?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
#    username: xiaowei
#    password: 123456
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    type: com.alibaba.druid.pool.DruidDataSource
#  druid:             
#    initial-size: 5            
#    min-idle: 5            
#    max-active: 20            
#    max-wait: 5000            
#  # 状态监控            
#    filter:                 
#        stat:                 
#        enabled: true                
#        db-type: mysql                
#        log-slow-sql: true                
#        slow-sql-millis: 2000            
#      # 监控过滤器            
#    web-stat-filter:                 
#        enabled: true                
#        exclusions:                 
#        - "*.js"                
#        - "*.gif"                
#        - "*.jpg"                
#        - "*.png"                
#        - "*.css"                
#        - "*.ico"                
#        - "/druid/*"            
#      # druid 监控页面            
#    stat-view-servlet:                 
#        enabled: true                
#        url-pattern: /druid/*                
#        reset-enable: false                
#        login-username: xiaowang                
#        login-password: 123456



